name: Tests

on: [push, pull_request]

jobs:
  my-job:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
      - name: Run Tests
        uses: matlab-actions/run-command@v2
        with:
          command: run_checks